# Generated by Django 3.2.2 on 2021-05-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumberChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=255, verbose_name='Выбор')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('type', models.CharField(choices=[('COMPANY', 'Для численности сотрудников компании'), ('STRIKE', 'Для численности участников')], max_length=255, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Выбор числа',
                'verbose_name_plural': 'Выбор чисел',
            },
        ),
        migrations.CreateModel(
            name='OwnerShipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Форма собственности',
                'verbose_name_plural': 'Формы собственности',
            },
        ),
    ]
