# Generated by Django 3.2.2 on 2021-05-13 09:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('strike', '0003_auto_20210513_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeUnion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Значение')),
                ('visible', models.BooleanField(default=False, verbose_name='Видимый')),
            ],
            options={
                'verbose_name': 'Есть ли на предприятии профсоюзы',
            },
        ),
        migrations.RemoveField(
            model_name='card',
            name='company',
        ),
        migrations.AddField(
            model_name='card',
            name='company_country_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Страна происхождения компании'),
        ),
        migrations.AddField(
            model_name='card',
            name='company_employees_count',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='employees_count', to='strike.numberchoices', verbose_name='Общая численность работников на предприятии'),
        ),
        migrations.AddField(
            model_name='card',
            name='company_is_tnk_member',
            field=models.BooleanField(default=False, verbose_name='Является ли эта кампания частью ТНК (Транснациональная компания)'),
        ),
        migrations.AddField(
            model_name='card',
            name='company_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Название предприятия (юридического лица)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='company_ownership_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='strike.ownershiptype', verbose_name='Форма собственности компании'),
        ),
        migrations.AddField(
            model_name='card',
            name='company_tnk_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название ТНК (Транснациональная компания)'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
